### ISSUE TITLE
Guidelines for Concurrent File I/O in Distributed Julia with BGZFStream and File-Level Locks

### ISSUE THREAD

**Issue by abhinavsns** [JuliaLang/Distributed.jl#109]
Hello,

I'm working on a distributed Julia application where multiple workers need to read and write to the same compressed file (e.g., BAM format) concurrently using BGZFStream. The application uses Distributed.jl to parallelize the workload across multiple workers. Here's a brief overview of the setup:

Reading: I use a reader (like XAM.BAM.Reader) that accesses specific regions of a large compressed file. The reader utilizes an index file to efficiently seek and read compressed bytes from different regions within the file.

Writing: Multiple workers may need to write to the same output file. I'm considering using BGZFStream with a file-level lock, such as:

```julia
BAM.Writer(BGZFStream(open(path, "w", lock=true), "w"))
```
Given this setup, I have the following questions:

Standard Guidelines for Distributed File I/O: What are the best practices or standard guidelines when performing file I/O in a distributed Julia environment, particularly with BGZFStream or similar compressed streams?

Locking Mechanisms: Is the file-level lock (lock=true) sufficient for ensuring safe concurrent reads and writes across multiple workers? Are there any additional considerations I should be aware of when using locks in a distributed environment?

Concurrent Reads: For reading, if multiple workers access different regions of the same file simultaneously, what should be considered to avoid conflicts or performance bottlenecks? Is there a standard approach for ensuring that concurrent reads are handled efficiently?

Potential Pitfalls: Are there known pitfalls or limitations when using Distributed.jl for file I/O with shared files? For example, is there a risk of file corruption or race conditions that I should take steps to mitigate?

Your insights on this would be incredibly valuable for distributed I/O operations are both safe and efficient.

Thank you for your assistance!

**Comment by vchuravy** [comment]
I think a better place to ask this question is https://discourse.julialang.org
