### ISSUE TITLE
Error if there is an space in `sshflags`  "-i path_to_ssh_key"

### ISSUE THREAD

**Issue by davidbp** [JuliaLang/Distributed.jl#111]
Hi 

I was trying to execute the following 

```julia
procs = addprocs([("dbp@ip:port", 4)], 
    dir="/home/dbp", 
    exename="/home/dbp/julia/bin/julia", 
    sshflags="-i path_to_ssh_key",
    tunnel=true,
)
```

but could not make it work. I was getting an error with message `path_to_ssh_key not accessible`, after asking in Discourse it was mentioned  to try  `sshflags="-ipath_to_ssh_key"` (without the space between -i and the path) and it worked.

In the documentation it is mentioned with an space

```
    •  sshflags: specifies additional ssh options, e.g. sshflags=`-i /home/foo/bar.pem`
```

**Comment by mgkuhn** [comment]
Try
```
procs = addprocs([("dbp@ip:port", 4)], 
    dir="/home/dbp", 
    exename="/home/dbp/julia/bin/julia", 
    sshflags=`-i path_to_ssh_key`,
    tunnel=true,
)
```
as the [documentation](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.addprocs) says. The grave accents (aka backticks) will create a [Cmd](https://docs.julialang.org/en/v1/base/base/#Base.Cmd) object, which is Julia's way to represent command-line arguments (which is internally a kind of string vector similar to `["-i", "path_to_ssh_key"]`).

If you use normal String quotes, you are passing a single ARGV element "-i path_to_ssh_key" to ssh, as if you had written `ssh "-i path_to_ssh_key"` on the command line, which is probably not what you wanted and which SSH won't understand.

**Comment by davidbp** [comment]
Hi, thank you for your explanation. I am so used to ``"this is as string"`` as well as ``'this is an string'`` (in python) that I did not realize `` `this was not a string` `` in julia. that makes sense.
