### ISSUE TITLE
Machinefile nonuniform install locations

### ISSUE THREAD

**Issue by dahlend** [JuliaLang/Distributed.jl#23]
There is little documentation for the format of machinefiles (not that it is very complex).

Currently machinefiles take number of procs, host, and ssh flags only, and assumes that the install location is conserved across systems (not the case for some of my work).  The only real way to solve the problem is to not use a host file.  It doesn't seem unreasonable to add some sort of option to the machinefile (I could do it pretty easily after trying to track this thing down).

It's just a little more string parsing, just a "dir=" and "exename=" option.

**Comment by vtjnash** [comment]
I think the decision was that `addprocs` in a julia script is already more flexible than this would be, which makes it simpler than inventing a new format
